import {prisma} from '../../prismaClient.js'; 
import { searchPostsContent as searchPostsContentSql } from '@prisma/client/sql'; // generated by `prisma generate --sql`

/** 
 * Create a new user
 * Returns: Promise<Prisma.User> 
 */ 
export function createUser(email, name, city) {
    return prisma.user.create({
      data: {
        email,
        name,
        city,
      },
    });
}

/**
 * Find users by city. Returns a Promise resolving to an array of users.
 * `Limit` may be undefined; service layer enforces defaults/clamps.
*/
export function findUsersByCity (cityName, limit) {
  const opts = {where: {city: cityName} };
  if(typeof limit === 'number') opts.take = limit;
  return prisma.user.findMany(opts);
}

/**
 * Delete a user by email.
 * Returns: Promise<Prisma.User>
 */
export function deleteUserByEmail(email) {
  return prisma.user.delete({
    where: { email },
    });
}

/**
 * Update a user's email.
 * Returns: Promise<Prisma.User>
 */
export function updateUserEmail(oldEmail, newEmail) {
  return prisma.user.update({
    where: { email: oldEmail },
    data: { email: newEmail },
    });
}

/**
 * Find users created in a date range.
 * startDate and endDate are passed to `new Date()` here
 * Service level validates/normalizes input first.
 * Returns: Promise<Prisma.User[]>
 */

export function newUsersByDateRange(startDate, endDate) {
  return prisma.user.findMany({
    where: {
      created_at: { 
        gte: new Date(startDate), 
        lte: new Date(endDate)       
      }
    },
    orderBy: { created_at: 'desc'}
  });
}

/**
 * Find published posts (with author and comments) since a date.
 * Returns the raw DB shape (service can transform comments to strings if desired).
 * Returns: Promise<Prisma.Post[]>
 */
export function publishedPostsAuthorCommentsSinceDate(startDate) {
  return prisma.post.findMany({
    where: {
      published: true,
      created_at: {gte: new Date(startDate)},
    },
    include: {
      author: {
        select: {
          id: true,
          name: true,
          city: true,
        }
      },
      comments: {
        select: {
          content: true
        }
      }
    },
    orderBy: {
      created_at: 'desc'
    }
  });
}

/**
 * Return the top N authors by published post count.
 * This returns the groupBy rows (author_id + _count). Service can fetch author details.
 * Returns: Promise<Array<{ author_id, _count: { author_id: number } }>>
 */
export function topAuthorsByPublishedCount(limit = 5) {
  // 1) Group & count only published posts per author
    return prisma.post.groupBy({
      by: ['author_id'],
      where: { published: true },          
      _count: { author_id: true },         
      orderBy: { _count: { author_id: 'desc' } }, 
      take: limit                             
    });
} 

/**
 * Get stats for active users (authors) who have >= minPublished published posts.
 * This returns the groupBy rows (author_id, _count, _max.created_at).
 * Service can use these results to fetch user rows or latest post content.
 * Returns: Promise<Array<{ author_id, _count, _max }>>
 */
  export function getActiveUserStats (minPublished = 5) {
    return prisma.post.groupBy({
      by: ['author_id'],
      where: {published: true},
      _count: {author_id: true},
      _max: {created_at: true}, //date of authors most recent post
      having: {
        author_id:{
          _count: {
            gte: minPublished
          }
        }
      },
      orderBy: {
        _count: {author_id: 'desc'}
      }
  });
  }

  /**
 * Trigram search implemented as TypedSQL helper call
 * Service layer should validate/normalize keyword and clamp limit before calling.
 * Returns: Promise<Array<any>>
 */
  export function searchPostsContent (searchText, limit = 50) {
    return prisma.$queryRawTyped(searchPostsContentSql(searchText, limit))
  }